name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  call-workflow-passing-data:
    uses: sschalasani/ci-cd-tools/.github/workflows/develop.yml@develop
    with:
      environment: dev
    secrets: inherit
