name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  call-workflow-passing-data:
    uses: sschalasani/ci-cd-tools/.github/workflows/develop.yml@develop
    with:
      config-path: ".github/labeler.yml"
      APP_NAME: my-app
      ENV: dev
      DEPLOY_TARGET: cloudhub
      DEPLOY_TARGET_TYPE: mule
    secrets:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
      PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
      CONNECTED_APP_CLIENT_ID: ${{ secrets.PLATFORM_USERNAME }}
      CONNECTED_APP_CLIENT_SECRET: ${{ secrets.PLATFORM_PASSWORD }}
