name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  call-workflow-passing-data:
    uses: sateeshc/ci-cd/.github/workflows/develop.yml@main
    with:
      environment: dev
    secrets: inherit
