name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: rhel8

    steps:
    - uses: actions/checkout@v4

    #- name: Set up JDK 17
    #  uses: actions/setup-java@v4
    #  with:
    #    java-version: '17'
    #    distribution: 'temurin'
    #    cache: maven

    - name: Build with Maven
      #run: mvn -B package --file pom.xml
      run: mvn -version

    - name: Run script file
      run: |
         export JAVA_HOME=$(dirname $(dirname `readlink -f /etc/alternatives/java`))
         echo $JAVA_HOME
         which java
         java -version
         javac c.java

         java c https://untrusted-root.badssl.com/
      shell: bash

