name: Java CI with Maven

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["main"]

env:
  app-components: "app1, net-tools-api, notifications-api"

jobs:
  Determine-changes:
    runs-on: ubuntu
    outputs:
      run-comps-matrix: ${{steps.outputs.outputs.run_comps_matrix }}

    steps:
      - id: outputs
        env:
          _APP_COMPONENTS: ${{ env.app-components }}
        run: |


          run_comps_matrix="{\"include\": ["
          run_comps_matrix+="]}"
          echo "run_comps_matrix=$run_comps_matrix"
          echo "run_comps_matrix=$run_comps_matrix" >> $GITHUB_OUTPUT
  call-workflow-passing-data:
    runs-on: ubuntu
    if: ${{ needs.Determine-changes.outputs.run-comps-matrix != '[]' }}
    strategy:
      matrix: ${{ fromJson(needs.Determine-changes.outputs.run-comps-matrix) }}
    #uses: sateeshc/ci-cd-tools/.github/workflows/develop.yml@develop
    steps:
      - name:
        env:
          _APP_COMPONENTS: ${{ env.app-components }}
        run: |
          echo "$_APP_COMPONENTS"
