name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]




jobs:
  call-workflow-passing-data:
    uses: sateeshc/ci-cd-tools/.github/workflows/develop.yml@develop
    with:
      config-path: ".github/labeler.yml"
    secrets: inherit


